function xlabel = defineXLabels

%  DEFINEXLABELS  Used to define the x labels a

%AK 7/05

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%         TAG                   LabelName       Color

xlabel = { ...
        'All',                              'All',             [0]; ...
        'Correct',                          'Correct',         [1]; ...
        'Error',                            'Error',           [2]; ... ...
        'LeftChoice',                       'Left',            [1]; ...
        'RightChoice',                      'Right',           [1]; ...
        'Stimulus=[1 2 7 8]',               'Easy',            [1]; ...
        'Stimulus=[3 4 5 6]',               'Diff',            [2]; ...
        'Stimulus=[1 2 7 8]&Correct',     'Corr Easy',         [1]; ...
        'Stimulus=[3 4 5 6]&Correct',     'Corr Diff',         [1]; ...
        'Stimulus=[1 8]&Correct',         'Corr Easy',         [1]; ...
        'Stimulus=[3 6]&Correct',         'Corr Med',          [2]; ...
        'Stimulus=[4 5]&Correct',         'Corr Diff',         [3]; ...
        'OdorRatio=[0 100]&Correct',      'Corr Easy',         [0]; ...
        'OdorRatio=[32 68]&Correct',      'Corr Med',          [32]; ...
        'OdorRatio=[32 44 56 68]&Correct','Corr Med',          [32]; ...
        'OdorRatio=[44 56]&Correct',      'Corr Diff',         [44]; ...
        'OdorRatio=[0 100]&Error',        'Err Easy',          [0]; ...
        'OdorRatio=[32 68]&Error',        'Err Med',           [32]; ...
        'OdorRatio=[32 44 56 68]&Error',  'Err Med',           [32]; ...
        'OdorRatio=[44 56]&Error',        'Err Diff',          [44]; ...
        'OdorRatio=[44 56]',              '44/56',             [44]; ...
        'OdorRatio=[32 68]',              '32/68',             [32]; ...
        'OdorRatio=[0 100]',              '0/100',             [0]; ...
        'OdorRatio=0',                    '0/100',             [0]; ...
        'OdorRatio=32',                   '32/68',             [32];   ...
        'OdorRatio=44',                   '44/56',             [44];   ...
        'OdorRatio=50',                   '50/50',             [50]; ...
        'OdorRatio=56',                   '56/44',             [56];   ...
        'OdorRatio=68',                   '68/32',             [68];   ...
        'OdorRatio=100',                  '100/0',             [100]; ...
        'OdorRatio=0&Correct',            '0/100 corr',        [0]; ...
        'OdorRatio=32&Correct',           '32/68 corr',        [32];   ...
        'OdorRatio=44&Correct',           '44/56 corr',        [44];   ...
        'OdorRatio=50&Correct',           '50/50 corr',        [50];  ...
        'OdorRatio=56&Correct',           '56/44 corr',        [56];   ...
        'OdorRatio=68&Correct',           '68/32 corr',        [68];   ...
        'OdorRatio=100&Correct',          '100/0 corr',        [100];   ...
        'OdorRatio=0&Error',              '0/100 err',         [0];  ...
        'OdorRatio=32&Error',             '32/68 err',         [32];  ...
        'OdorRatio=44&Error',             '44/56 err',         [44];  ...
        'OdorRatio=50&Error',             '50/50 err',         [50];  ...
        'OdorRatio=56&Error',             '56/44 err',         [56];  ...
        'OdorRatio=68&Error',             '68/32 err',         [68];  ...
        'OdorRatio=100&Error',            '100/0 err',         [100]; ...
    };

